name: dtakt_fahrplan_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.3.0
  intl: any
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/google_fonts/comfortaa/
    - assets/google_fonts/notosans/OFL.txt
    - assets/google_fonts/roboto/OFL.txt
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/google_fonts/notosans/NotoSans-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/google_fonts/roboto/Roboto-Regular.ttf
  generate: true
  uses-material-design: true
