server:
  port: 8080
  web_folder: ui_flutter
timetable:
  datasets:
    dtakt:
      path: dtakt-gtfs.zip
      default_bikes_allowed: false
street_routing: false
geocoding: true
osr_footpath: false
